# Buildpack API version
api = "0.2"

[buildpack]
id = "buildpacks/python"
version = "0.0.1"
name = "Empty Buildpack"
homepage = "https://github.com/future-architect/"

[[stacks]]
id = "shinofarastack"
