FROM golang:1.14

LABEL io.buildpacks.stack.id="io.github.future-architect.samples.debian1"

RUN addgroup --gid 1000 builder
RUN useradd -ms /bin/bash -u 1000 -g 1000 builder

USER builder

WORKDIR /home/builder

ENV CNB_STACK_ID="io.github.future-architect.samples.debian1"
ENV CNB_USER_ID="1000"
ENV CNB_GROUP_ID="1000"